### ISSUE TITLE
xcode live rendering issue

### ISSUE THREAD

**Issue by priyankagaikwad** [Daij-Djan/DDCalendarView#15]
@Daij-Djan 
file:///DDCalendarView-master/Demos/CalendarDemo_objc/Base.lproj/Main.storyboard: error: IB Designables: Failed to update auto layout status: The agent crashed

file:///DDCalendarView-master/Demos/CalendarDemo_objc/Base.lproj/Main.storyboard: error: IB Designables: Failed to render instance of DDCalendarView: The agent crashed

recently facing these two errors in storyboard live rendering
xcode version 7.3  
iOS 9.2

**Comment by Daij-Djan** [comment]
thats not something I cant reproduce. but I also dont support xcode7 anymore.

works fine here :)
