### ISSUE TITLE
Can we add another view for canceling the events in DDCalendar view ? 

### ISSUE THREAD

**Issue by YogeshBharate** [Daij-Djan/DDCalendarView#16]
Can we add another view for canceling (like cross icons or image) the events in DDCalendar view ? IF yes then please how to add it ?

**Comment by Daij-Djan** [comment]
sure. as a subview of the eventView you can add anything you like.

event views work like UITableViewCells. 

I'd start by reading through some tableView related tutorials to get a feel for the api
