### ISSUE TITLE
Project in Swift shows no event list

### ISSUE THREAD

**Issue by StefanPrifti** [Daij-Djan/DDCalendarView#3]
I've managed to show DDCalendarView in my project in Swift, but no event list is showing. I just want to know how to add some dummy data to this view to test it out. I'm new to iOS development so please bear with me :smile: 

![screen shot 2016-01-10 at 21 05 45](https://cloud.githubusercontent.com/assets/5692026/12223938/b1364838-b7e4-11e5-9b84-cbb1b5f86d13.png)

**Comment by Daij-Djan** [comment]
the swift example does not work with mock data but by showing your real ical data

the EKEventStore on the simulator does not return any of the mac's calendars.
Plz try on a real device
