### ISSUE TITLE
Can we use this to create week view?

### ISSUE THREAD

**Issue by priyankagaikwad** [Daij-Djan/DDCalendarView#5]
Can we use this to create week view? Anybody tried this?

**Comment by Daij-Djan** [comment]
hi. this could easily be added :) right now I only show 1 day view. I could just show 7 day views. Ill add it tomorrow

**Comment by priyankagaikwad** [comment]
Thank you in advance

**Comment by priyankagaikwad** [comment]
Hi Daij-Djan,
I am stuck on week view with events.Please add it soon if possible. Thank you :)

**Comment by Daij-Djan** [comment]
I am on it! It was more work then I originally anticipated :)
I got it working alright today and I will finalize the code tomorrow

**Comment by Daij-Djan** [comment]
updated my control with week view, more l&f and performance - awaiting bugreports before pushing it out via #cocoapods

plz test it

**Comment by priyankagaikwad** [comment]
I tried this and its working fine in objective-c but when I used this with swift it is returning numberOfDays 1 and not 7 for delegate methods though I set numberOfDays = 7
Thank you

**Comment by priyankagaikwad** [comment]
Hi Daij-Djan,
Is it working with swift? I am facing some issues to view events when using swift.
