### ISSUE TITLE
Is it possible to show vertical border lines between days columns?

### ISSUE THREAD

**Issue by sebastienkb** [Daij-Djan/DDCalendarView#7]
Hi,

When I first fired the demo app I put it in portrait (constraint in my app) and didn't even notice it was showing 7 days because I expected at least some border between days. I think it would be nice to be able to draw a vertical line between each day. Is this possible? If yes, how can we customise that? If no, can this be added with color customisation?

Thank you

Sébastien

**Comment by Daij-Djan** [comment]
added now
